// Code generated by mockery v2.53.6. DO NOT EDIT.

package domain

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockLessonPort is an autogenerated mock type for the LessonPort type
type MockLessonPort struct {
	mock.Mock
}

// GetLessonsByDate provides a mock function with given fields: ctx, start, end
func (_m *MockLessonPort) GetLessonsByDate(ctx context.Context, start time.Time, end time.Time) []Lesson {
	ret := _m.Called(ctx, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetLessonsByDate")
	}

	var r0 []Lesson
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []Lesson); ok {
		r0 = rf(ctx, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Lesson)
		}
	}

	return r0
}

// NewMockLessonPort creates a new instance of MockLessonPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLessonPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLessonPort {
	mock := &MockLessonPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
